name: galliumhook Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Enable MSVC Developer Command Prompt
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.0
      with:
        vsversion: "2022"
        arch: "amd64"

    # Build the library
    - name: Build galliumhook
      run: msbuild galliumhook\galliumhook.sln /p:Configuration=$env:Configuration /p:Platform=$env:Platform
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    # Upload the built files
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: galliumhook - ${{ env.Platform }} ${{ env.Configuration }}
        path: galliumhook\${{ env.Platform }}\${{ env.Configuration }}
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
